name = "CFDomains"
uuid = "3699aaca-035b-4155-96ec-eecb526248de"
authors = ["The ClimFlows contributors"]
version = "0.3.13"

[deps]
ManagedLoops = "36a4119d-6b73-4371-88fe-ba2d91f5495d"
MutatingOrNot = "6a37069a-9a67-4b2d-a34a-f09ab4b23c7c"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
SHTnsSpheres = "9e5c175a-5132-4517-85a1-2957ec255f89"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[extensions]
SHTnsSpheres_Ext = ["SHTnsSpheres"]
CFDomainsAdaptExt = ["Adapt"]
CFDomainsMooncakeExt = ["Mooncake"]
CFDomainsSIMDExt = ["ForwardDiff", "SIMD"]
CFDomainsForwardDiffExt = ["ForwardDiff"]

[compat]
Adapt = "4"
ManagedLoops = "0.1.11"
PackageExtensionCompat = "1"
SHTnsSpheres = "0.2.16"
julia = "1.8"

[extras]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
SHTnsSpheres = "9e5c175a-5132-4517-85a1-2957ec255f89"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
